[package]
name = "plabble-codec"
version = "0.1.0"
edition = "2024"
description = "Plabble Transport Protocol codec"
license = "BSD-3-Clause"
categories = ["cryptography", "encoding", "chat", "plabble"]
repository = "https://github.com/plabble/ptp-codec"

[lib]
name = "plabble_codec"
crate-type = ["rlib"]

[dependencies]
aes = "0.8.4"
aes-gcm = "0.10.3"
base64 = "0.22.1"
binary-codec = "0.5.9"
blake2 = "0.10.6"
blake3 = { version = "1.8.2", optional = true }
ctr = "0.9.2"
cipher = "0.4.4"
chacha20 = "0.9.1"
chacha20poly1305 = "0.10.1"
chrono = { version = "0.4.42", features = ["serde"] }
ed25519-dalek = "2.2.0"
log = "0.4.29"
ml-dsa = { version = "0.0.4", optional = true }
ml-kem = { version = "0.2.1", optional = true }
serde = { version = "1.0.225", features = ["derive"] }
serde-value = "0.7.0"
serde_with = { version = "3.14.0", features = ["base64", "hex"] }
x25519-dalek = { version = "2.0.1", features = ["static_secrets"] }

# Dependency fuckup with rand...
rand_core_064 = { package = "rand_core", version = "0.6.4", features = ["getrandom"]}

[features]
default = ["blake-3", "pqc-lite", "pqc-heavy"]
blake-3 = ["blake3"]
pqc-lite = ["ml-dsa", "ml-kem"]
pqc-heavy = []

[dev-dependencies]
toml = "0.9.7"
hex = "0.4.3"
serde_json = "1.0.148"
env_logger = "0.11.8"
