[package]
name = "plabble-codec"
version = "0.1.0"
edition = "2024"
description = "Plabble Transport Protocol codec"
license = "BSD-3-Clause"
categories = ["cryptography", "encoding", "chat", "plabble"]
repository = "https://github.com/plabble/ptp-codec"

[lib]
name = "plabble_codec"
crate-type = ["rlib"]

[dependencies]
binary-codec = "0.2.9"
serde = { version = "1.0.225", features = ["derive"] }
serde-value = "0.7.0"
serde_with = { version = "3.14.0", features = ["base64"] }
toml = "0.9.7"
